apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-azure-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-azure
  template:
    metadata:
      labels:
        app: hello-azure
    spec:
      containers:
      - name: hello-azure
        image: hello-azure-world:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000